name: Check Renderability

on:
  pull_request:

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: Verify nonexistence of `rendered`
        shell: bash
        run: if [ -e rendered ]; then exit 1; fi

      - name: Compile ZIPs and Zcash Protocol Specification
        uses: ./.github/actions/render
